In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("ks-projects-201801.csv")

In [3]:
data.head(2)

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00

In [4]:
data.describe()

,ID,goal,pledged,backers,usd pledged,usd_pledged_real,usd_goal_real
count,3.786610e+05,3.786610e+05,3.786610e+05,378661.000000,3.748640e+05,3.786610e+05,3.786610e+05
mean,1.074731e+09,4.908079e+04,9.682979e+03,105.617476,7.036729e+03,9.058924e+03,4.545440e+04
std,6.190862e+08,1.183391e+06,9.563601e+04,907.185035,7.863975e+04,9.097334e+04,1.152950e+06
min,5.971000e+03,1.000000e-02,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,1.000000e-02
25%,5.382635e+08,2.000000e+03,3.000000e+01,2.000000,1.698000e+01,3.100000e+01,2.000000e+03
50%,1.075276e+09,5.200000e+03,6.200000e+02,12.000000,3.947200e+02,6.243300e+02,5.500000e+03
75%,1.610149e+09,1.600000e+04,4.076000e+03,56.000000,3.034090e+03,4.050000e+03,1.550000e+04
max,2.147476e+09,1.000000e+08,2.033899e+07,219382.000000,2.033899e+07,2.033899e+07,1.663614e+08

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                378661 non-null  int64
 1   name              378657 non-null  object
 2   category          378661 non-null  object
 3   main_category     378661 non-null  object
 4   currency          378661 non-null  object
 5   deadline          378661 non-null  object
 6   goal              378661 non-null  float64
 7   launched          378661 non-null  object
 8   pledged           378661 non-null  float64
 9   state             378661 non-null  object
 10  backers           378661 non-null  int64
 11  country           378661 non-null  object
 12  usd pledged       374864 non-null  float64
 13  usd_pledged_real  378661 non-null  float64
 14  usd_goal_real     378661 non-null  float64
dtypes: float64(5), int64(2), object(8)
memory usage: 43.3+ MB

In [6]:
data.dropna(inplace=True)
data.drop(axis=0,labels=data[data["name"]=="Null"].index,inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 374859 entries, 0 to 378660
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                374859 non-null  int64
 1   name              374859 non-null  object
 2   category          374859 non-null  object
 3   main_category     374859 non-null  object
 4   currency          374859 non-null  object
 5   deadline          374859 non-null  object
 6   goal              374859 non-null  float64
 7   launched          374859 non-null  object
 8   pledged           374859 non-null  float64
 9   state             374859 non-null  object
 10  backers           374859 non-null  int64
 11  country           374859 non-null  object
 12  usd pledged       374859 non-null  float64
 13  usd_pledged_real  374859 non-null  float64
 14  usd_goal_real     374859 non-null  float64
dtypes: float64(5), int64(2), object(8)
memory usage: 45.8+ MB

In [7]:
x=data[data["name"].str.lower().str.contains("wallet")].groupby(by="category").mean()
x["ratio"]=x["usd_pledged_real"]/x["usd_goal_real"]
x.sort_values(by="ratio", ascending=False)

,ID,goal,pledged,backers,usd pledged,usd_pledged_real,usd_goal_real,ratio
category,,,,,,,,
Interactive Design,5.659388e+08,1.000000,2067.000000,127.000000,2067.000000,2067.000000,1.000000,2067.000000
Games,1.016380e+09,8750.000000,30195.000000,570.000000,16330.000000,30195.000000,8750.000000,3.450857
Gadgets,1.131418e+09,21119.520000,65892.344400,550.160000,65344.434400,67309.371200,21633.900400,3.111292
Art,1.260814e+09,400.000000,1243.000000,20.000000,1243.000000,1243.000000,400.000000,3.107500
Wearables,1.162493e+09,18000.000000,48479.350000,439.857143,43697.409286,48564.918571,18460.527143,2.630744
Hardware,7.067961e+08,22571.428571,46237.310000,748.571429,43441.881429,46237.310000,22571.428571,2.048488
Product Design,1.082147e+09,10812.248611,18145.918389,371.519444,11374.503000,17579.905931,9019.083958,1.949190
Design,1.093200e+09,8640.579439,14341.212056,354.598131,12699.888318,14056.519159,7534.385514,1.865649
Fashion,1.044910e+09,8754.315789,15435.482456,500.500000,15812.265526,15857.155263,9061.491404,1.749950
Technology,1.156441e+09,17920.851852,24536.153333,314.407407,16638.968519,24944.031852,17887.424815,1.394501
Accessories,1.050540e+09,8059.521053,10452.465789,212.536842,7027.136105,8722.616158,7115.010158,1.225946
Crafts,1.008081e+09,3131.250000,3720.287500,65.312500,3506.598750,3757.123125,3183.764375,1.180088
3D Printing,4.287037e+08,4000.000000,1932.000000,82.000000,1396.560000,1391.530000,2881.010000,0.483001
Apparel,1.086436e+09,7502.500000,2718.333333,49.666667,2557.350000,2723.305000,7334.628333,0.371294
Tabletop Games,7.788259e+08,27741.666667,10392.721667,175.166667,7670.635000,9865.078333,27479.543333,0.358997
Woodworking,1.531150e+09,8333.333333,2264.333333,49.000000,2137.313333,2156.646667,7621.633333,0.282964
Shorts,1.499266e+09,500.000000,125.000000,3.000000,160.090000,160.510000,642.050000,0.249996
Publishing,8.701426e+08,2000.000000,352.000000,20.000000,325.000000,352.000000,2000.000000,0.176000
Indie Rock,2.443969e+08,200.000000,34.000000,2.000000,0.000000,36.250000,213.220000,0.170012
Jewelry,1.060957e+09,12000.000000,1437.000000,35.000000,1632.090000,1535.860000,12825.580000,0.119750
Theater,1.218792e+09,2135.000000,190.000000,8.000000,190.000000,190.000000,2135.000000,0.088993
DIY,1.031952e+09,7016.666667,92.333333,3.333333,92.333333,92.333333,1204.373333,0.076665
Footwear,2.138040e+09,7765.000000,533.000000,9.000000,533.000000,533.000000,7765.000000,0.068641
Film & Video,5.566677e+08,99000.000000,4407.000000,20.000000,4407.000000,4407.000000,99000.000000,0.044515
People,1.257484e+07,2000.000000,35.000000,3.000000,35.000000,35.000000,2000.000000,0.017500
Installations,9.515721e+08,500.000000,5.000000,1.000000,8.290000,8.150000,815.420000,0.009995
Software,6.834775e+08,15762.500000,89.000000,3.500000,87.000000,89.000000,15762.500000,0.005646
Apps,1.229521e+09,61013.333333,188.333333,6.000000,188.333333,188.333333,61013.333333,0.003087
Drinks,3.870141e+08,198000.000000,470.000000,12.000000,470.000000,470.000000,198000.000000,0.002374
Ready-to-wear,1.813339e+09,2900.000000,1.000000,1.000000,1.000000,1.000000,2900.000000,0.000345
Music,1.365848e+09,2500.000000,0.000000,0.000000,0.000000,0.000000,2500.000000,0.000000
Stationery,7.914159e+08,50000.000000,0.000000,0.000000,0.000000,0.000000,51902.750000,0.000000

In [8]:
y=data[data["name"].str.lower().str.contains("djin")]
y["ratio"]=y["usd_pledged_real"]/y["usd_goal_real"]
y.sort_values(by="ratio", ascending=False)

C:\Users\jinve\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,ratio
151530,1769983909,"DJIN: The Wallet, perfected.",Product Design,Design,USD,2017-08-27,25000.0,2017-06-28 19:59:57,541167.0,successful,10165,US,20066.00,541167.00,25000.00,21.646680
16865,1085457767,Lord of Djinn,Video Games,Games,USD,2014-10-29,4000.0,2014-09-19 07:01:21,5073.0,successful,54,US,5073.00,5073.00,4000.00,1.268250
83622,1425193047,Dream of the Djinn Tabletop RPG Adventure,Tabletop Games,Games,AUD,2015-11-07,3550.0,2015-10-08 04:44:21,3638.0,successful,54,AU,2576.13,2597.27,2534.45,1.024786
186392,1948768542,Chessia Trick's Slipmat Shoppe- DJing with an ...,Illustration,Art,USD,2015-02-10,1700.0,2015-01-09 21:04:29,460.0,failed,7,US,460.00,460.00,1700.00,0.270588
8765,1044261098,Djinesin,Fiction,Publishing,USD,2014-01-01,1000.0,2013-12-02 23:15:09,50.0,failed,5,US,50.00,50.00,1000.00,0.050000
329498,748795827,Djinn Wars,Comics,Comics,USD,2011-10-12,5228.0,2011-09-12 20:20:11,12.0,failed,3,US,12.00,12.00,5228.00,0.002295
50606,1257672864,Djinn,Film & Video,Film & Video,USD,2013-02-12,16500.0,2013-01-03 23:44:40,26.0,failed,2,US,26.00,26.00,16500.00,0.001576
68115,1346728799,disabled man with a dream of djing again,Music,Music,USD,2014-09-14,5000.0,2014-07-16 00:28:10,0.0,failed,0,US,0.00,0.00,5000.00,0.000000
176062,1895544988,Emancipate the Djinni Album,Electronic Music,Music,USD,2013-12-24,11000.0,2013-11-21 21:42:39,0.0,failed,0,US,0.00,0.00,11000.00,0.000000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 374859 entries, 0 to 378660
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                374859 non-null  int64
 1   name              374859 non-null  object
 2   category          374859 non-null  object
 3   main_category     374859 non-null  object
 4   currency          374859 non-null  object
 5   deadline          374859 non-null  object
 6   goal              374859 non-null  float64
 7   launched          374859 non-null  object
 8   pledged           374859 non-null  float64
 9   state             374859 non-null  object
 10  backers           374859 non-null  int64
 11  country           374859 non-null  object
 12  usd pledged       374859 non-null  float64
 13  usd_pledged_real  374859 non-null  float64
 14  usd_goal_real     374859 non-null  float64
dtypes: float64(5), int64(2), object(8)
memory usage: 45.8+ MB

In [10]:
#data["Search"]="https://www.kickstarter.com/discover/advanced?ref=nav_search&term="+data["name"]
#data["Search"][0]

In [11]:
data.to_csv("2018_kickstarter.csv", sep=',',index=False)

In [12]:
data.shape

(374859, 15)

In [20]:
data["goall"]=data["usd_pledged_real"]*100/data["usd_goal_real"]
data

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,goall
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95,0.000000
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00,8.070000
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00,0.488889
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00,0.020000
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00,6.579487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,Film & Video,USD,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,canceled,1,US,25.0,25.0,50000.00,0.050000
378657,999977640,The Tribe,Narrative Film,Film & Video,USD,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,failed,5,US,155.0,155.0,1500.00,10.333333
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,Film & Video,USD,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,failed,1,US,20.0,20.0,15000.00,0.133333
378659,999987933,BioDefense Education Kit,Technology,Technology,USD,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,failed,6,US,200.0,200.0,15000.00,1.333333
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,Art,USD,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,failed,17,US,524.0,524.0,2000.00,26.200000

In [28]:
x=data.groupby(by="category").mean()